services:
  frontend:
    image: nginx
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/src/:/etc/nginx/src
      # hacky solution for compiled typescript files
      - ./frontend/build/:/etc/nginx/build
    ports:
      - 8080:80
  converter:
    image: converter
    build:
      context: converter